version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 83:80/tcp #WEBUI
    volumes:
      - /mnt/hdd/docker/adguard-home/work:/opt/adguardhome/work
      - /mnt/hdd/docker/adguard-home/conf:/opt/adguardhome/conf
      - /mnt/hdd/docker/adguard-home/tmp:/tmp