version: "3"
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /mnt/hdd/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt/hdd/docker/homeassistant/broadlink/:/usr/local/lib/python3.10/site-packages/broadlink/ #For broadlink support RM4C Mini
    restart: always
    privileged: true
    network_mode: host