version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Santiago
#      - MYSQL_DATABASE=USER_DB_NAME #optional
#      - MYSQL_USER=MYSQL_USER #optional
#      - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
#      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /mnt/hdd/docker/mariadb/config:/config
      - /mnt/hdd/docker/mariadb/tmp:/tmp
    ports:
      - 3306:3306
    restart: always
   
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8086:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=192.168.1.123