version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "83:80/tcp"
    environment:
      TZ: 'America/Santiago'
      WEBPASSWORD: 'admin'
    volumes:
      - /mnt/hdd/docker/pihole/etc-pihole/:/etc/pihole/
      - /mnt/hdd/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always