version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Santiago
      - TRANSMISSION_WEB_HOME=/flood-for-transmission/ #/combustion-release/, /transmission-web-control/, /kettu/ and /flood-for-transmission/.
      - USER=admin
      - PASS=admin
    volumes:
      - /mnt/hdd/docker/transmission/config:/config
      - /mnt/hdd/docker/transmission/downloads:/downloads
      - /mnt/hdd/docker/transmission/watch:/watch
      - /mnt/hdd/docker/transmission/tmp:/tmp
    ports:
      - 8082:9091
      - 51413:51413
      - 51413:51413/udp
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

#  jackett:
#    image: ghcr.io/linuxserver/jackett
#    container_name: jackett
#    environment:
#      - PUID=1000
#      - PGID=1000
#      - TZ=America/Santiago
#      - AUTO_UPDATE=true #optional
##      - RUN_OPTS=<run options here> #optional
#    volumes:
#      - /mnt/hdd/docker/jackett/config:/config
#      - /mnt/hdd/docker/jackett/downloads:/downloads
#      - /mnt/hdd/docker/jackett/tmp:/tmp
#    ports:
#      - 9117:9117
#    restart: unless-stopped
#
#  sonarr:
#    image: ghcr.io/linuxserver/sonarr
#    container_name: sonarr
#    environment:
#      - PUID=0
#      - PGID=0
#      - TZ=America/Santiago
#    volumes:
#      - /mnt/hdd/docker/sonarr/config:/config
#      - /mnt/hdd/docker/sonarr/tvseries:/tv #optional
#      - /mnt/hdd/docker/transmission/downloads:/downloads #optional
#    ports:
#      - 8989:8989
#    restart: unless-stopped
#
#  radarr:
#    image: ghcr.io/linuxserver/radarr
#    container_name: radarr
#    environment:
#      - PUID=0
#      - PGID=0
#      - TZ=America/Santiago
#    volumes:
#      - /mnt/hdd/docker/radarr/config:/config
#      - /mnt/hdd/docker/radarr/movies:/movies #optional
#      - /mnt/hdd/dockerps/transmission/downloads:/downloads #optional
#    ports:
#      - 7878:7878
#    restart: unless-stopped